### ISSUE TITLE
Display die() text on termination

### ISSUE THREAD

**Issue by maiku41** [raix/vscode-perl-debug#13]
When die() is executed, the debugger output window says "ERR>Continue error: undefined​​".

Display whatever was passed to die().  For reference, perl5db.pl currently does this:

  DB<1> die "some text here"
some text here at (eval 8)[/usr/share/perl/5.22/perl5db.pl:737] line 2.

**Comment by raix** [comment]
Mental note: This might also block regular output eg. hitting "continue" without break points will end the stream before all output has landed.

**Comment by raix** [comment]
should be fixed, released in [0.2.0](https://github.com/raix/vscode-perl-debug/releases/tag/v0.2.0) - please reopen if the issue persists
