### ISSUE TITLE
If you have a space in the folder name where your file is located then perl-debug doesn't work.

### ISSUE THREAD

**Issue by hpta** [raix/vscode-perl-debug#133]
Well this caused much frustration today because it's not obvious at all. So please either fix it or put this info near the very top of the VScode marketplace webpage so one can make a note of it.

No error is shown, lefthand side debug panels are empty.

I am on Windows and I've tested this on identical files with these paths.

"C:\Users\username\Documents\pokus\1.pl"            // OK
"C:\Users\username\Documents\pokus 2\2.pl"        // debug doesn't work as expected

**Comment by raix** [comment]
We currently have an issue with spaces in filenames

**Comment by GitMensch** [comment]
Is this any different from #104 ? If yes: specify how, if not please close as duplicate.

**Comment by hpta** [comment]
I'm closing is as a duplicate of [#104 ](https://github.com/raix/vscode-perl-debug/issues/104)
