### ISSUE TITLE
exec arguments

### ISSUE THREAD

**Issue by avances123** [raix/vscode-perl-debug#14]
I see there is a `inc` array, seems reasonable to have another like `arguments` to pass to the perl program?

**Comment by raix** [comment]
@avances123 sounds reasonable

**Comment by raix** [comment]
Added in `0.1.7` just released.
I'm closing this ticket - but let me know if you encounter issues with this feature

https://github.com/raix/vscode-perl-debug/releases/tag/v0.1.7
