### ISSUE TITLE
Unable to debug with autogenerated launch configs

### ISSUE THREAD

**Issue by kshkrao3** [raix/vscode-perl-debug#15]
I have below auto-generated `launch.json` configs.

```
{
    "version": "0.0.2",
    "configurations": [{
       "type": "perl",
        "request": "launch",
        "exec": "perl",
        "name": "Perl-Debug",
        "root": "${workspaceRoot}/",
        "program": "${workspaceRoot}/${command.AskForProgramName}",
        "inc": [],
        "stopOnEntry": true
    }]
}

```

I have a simple file within `workspaceRoot` named as **`testPerl.pl`** and its contents are as below.

```
$p="Welcome to perl\n";
print $p;

print "What is your name?\n";
my $name=readline STDIN;
chomp($name);
print "Welcome $name\n";

```

But no matter what, I am not able to debug this file even after placing debuggers. It doesn't throw any error, it doesn't logs/prints anything. It just starts and stops.

I have also tried to update `"program"` values to `"program": "${workspaceRoot}/test.pl",`  and `"program": "${workspaceRoot}/${relativeFile}",` but did not make a way to run it successfully. 

Screenshot attached for a reference to `workspaceRoot` structure.

![image](https://cloud.githubusercontent.com/assets/11007754/22102745/8cd232b2-de5e-11e6-9e3c-89fcddfed418.png)

How could I possibly debug this file? Any other things I need to try?

**Comment by raix** [comment]
@kshkrao3 it's a good question,

Options:
* try removing the readline part of the code
* try to run the `perl -d test.pl` manually to verify that the debugger etc. is working
* install `PadWalker`

What perl distribution+version are you using? (I've setup a test matrix for some but not all distributions/versions)

**Comment by kshkrao3** [comment]
**- try removing the readline part of the code**
  I tried this, but still was on same track of issue.

**- try to run the perl -d test.pl manually to verify that the debugger etc. is working**
When I try to run `perl -d test.pl`, I was getting below error. Couldn't get much detail on the resolution.
```
Loading DB routines from perl5db.pl version 1.49_05
Editor support available.

Enter h or 'h h' for help, or 'perldoc perldebug' for more help.

main::(test.pl:2):      $p="Welcome to perl\n";
Unable to get Terminal Size. The Win32 GetConsoleScreenBufferInfo call didn't work. The COLUMNS and LINES environment variables didn't work. at C:/apache/perl/lib/Term/ReadLine/readline.pm line 410.
 at C:/apache/perl/lib/Term/ReadKey.pm line 462.
        Term::ReadKey::GetTerminalSize(GLOB(0x2597bd0)) called at C:/apache/perl/lib/Term/ReadLine/readline.pm line 410
        readline::get_window_size called at C:/apache/perl/lib/Term/ReadLine/readline.pm line 1117
        readline::init called at C:/apache/perl/lib/Term/ReadLine/readline.pm line 208
        require Term/ReadLine/readline.pm called at C:/apache/perl/lib/Term/ReadLine/Perl.pm line 65
        eval {...} called at C:/apache/perl/lib/Term/ReadLine/Perl.pm line 65
        Term::ReadLine::Perl::new("Term::ReadLine", "perldb", GLOB(0x27e6730), GLOB(0x2597bd0)) called at C:/apache/perl/lib/perl5db.pl line 6864
        DB::setterm() called at C:/apache/perl/lib/perl5db.pl line 1845
        DB::_DB__read_next_cmd(undef) called at C:/apache/perl/lib/perl5db.pl line 2782
        DB::DB called at test.pl line 2
  DB<1> main::(test.pl:3):      print $p;
  DB<1> Welcome to perl

```

Could this be the problem?

**- install PadWalker**

Is this extension for Visual Studio Code. Couldn't find it for the same though.


Sorry if am misleading anywhere, but am loosing  this..

**Comment by raix** [comment]
PadWalker is a perl module you might need to install on your system eg. with cpan etc.

The output about terminal size is most likely the issue - is that occuring when you run it from a terminal or is that output comming from vscode?

**Comment by kshkrao3** [comment]
Its occurring when running through terminal..

**Comment by raix** [comment]
what distribution of perl are you using?

**Comment by kshkrao3** [comment]
The latest one. i.e. 5.24.1.

**Comment by raix** [comment]
is it activeperl/strawberry/citrus/cygwin etc.?

**Comment by kshkrao3** [comment]
Oh sorry, my bad.. Its activeperl..

**Comment by raix** [comment]
just, released [0.2.0](https://github.com/raix/vscode-perl-debug/releases/tag/v0.2.0) - please check if this issue persists - I've done some cleanups to the extension itself

**Comment by raix** [comment]
@kshkrao3 I just released `v0.2.1`, I've added more versions of activeperl in the test matrix - and started on "adapter" tests.

I've added a "trace" option in the settings - this should dump debug info from the extension.

I also fixed the autogeneration of default settings file - should support windows users now...

please let me know if this is still an issue - it might be something that isn't 100% an issue with the extension but we might be able to add documentation in the wiki, might help others.

The extension should set the `COLUMNS` and `LINES` environment variables - but I'm wondering why it complains about your terminal - what terminal program are you using?

**Comment by kshkrao3** [comment]
@raix Am sorry to say, but I've stopped working on this very long back. If I could contribute anything to this repo, then please let me know and if you want me to test this, definitely I would do it as part of contribution..

Appreciate for follow up and your efforts..

**Comment by pwr22** [comment]
That warning shouldn't be fatal and as can be seen from the manual `perl -d` output above, the debugger doesn't care

**Comment by pwr22** [comment]
The reason there may be no output in the debugger through VSCode may be a buffering issue, I've observed this myself. Set `$| = 1` at the top of the script and you may then get output

**Comment by raix** [comment]
@pwr22 thanks - I'll have to investigate buffering issue

**Comment by raix** [comment]
I've added a notification about missing padwalker in 0.4.0 and switched output to "hot" using `$| = 1` (currently being build and released).

Closing this issue - let me know if the issue persists

**Comment by edo101** [comment]
I used pwr22's suggestion and that fixed the issue for me in VScode. Not sure why it works but I'm happy. Using Komodo IDE's debugger is annyoing cause it pops up a configuration menu each time
