### ISSUE TITLE
Debugging applications with carton managed INCS

### ISSUE THREAD

**Issue by carragom** [raix/vscode-perl-debug#17]
Hi there,

I would like to debug a Mojolicious app with this plugin, using **carton** as dependency manager. The end result of the debug command should be something like this:

    carton exec -- perl -d ./local/bin/morbo script/myapp

Here carton would be the actual program to run, everything else is just parameters. Using **carton** is very convenient as it allows dependencies to live under the _./local_ directory of the project just like npm install under the local node_modules.

I started working towards this goal on a fork and managed to get it working using extra configuration options, something like:

```json
{
    "exec": "carton",
    "execParams": [
        "exec",
        "--",
        "perl"
    ],
    "program": "./local/bin/morbo",
    "programParams": [
        "script/myapp"
    ]
}
```

The debugger was successfully launched but then paths did not match, most were duplicated and VSCode could not find them. So I decided to ask here about the scope of this plugin and if it would make sense to try to implement a feature like this.

**Comment by raix** [comment]
makes sense - could you try something like:
```json
{
  "exec": "carton exec -- perl",
  "program": "morbo",
  "args": [
    "script/myapp"
  ]
}
```

**Comment by carragom** [comment]
Hi,

Yes, that was my first attempt, but turns out that [here](https://github.com/raix/vscode-perl-debug/blob/master/src/adapter.ts#L247) `spawn` would treat `carton exec -- perl` as the executable name and fail to run it. two options come to mind:

1- Have a separated `args` parameter for `exec`.
2- Split `exec` by spaces, run the first item and pass the rest as parameters. This would fail if a parameter value contains a space. Something like `-n "my name"`.

Any other idea how to handle this?

**Comment by raix** [comment]
I'm voting for option 1 - it's safe/easy to reason about.
We Can add as 'execArgs' that takes an array of strings?
It is closely related to the 'inc' implementation

**Comment by raix** [comment]
@carragom The code is done - I'll release later this week
