### ISSUE TITLE
Debug doesn't work since the last release 0.2.0

### ISSUE THREAD

**Issue by Resousse** [raix/vscode-perl-debug#19]
Hi,

I did the extension update and the debug of my program is not working anymore.
I have not much experience in Perl, but my program was working yesterday with the version 0.1.8.
The only error message I have is : 
`onException: Can't find Unicode property definition "e" in regex; marked by <-- HERE in m/^_<.*c:\Users\user\Desktop\FED\pe <-- HERE licanos.pl/
`
Also, is it possible to install an older version of a VSCode extension? 
Thanks!

**Comment by raix** [comment]
Hi, the onException is logged in the debug console on exceptions when running the perl program.

Does this only happen when running the debugger from vs code? *(or does this also happen when running `$ perl -d my_code.pl` in the terminal?)*

**Comment by Resousse** [comment]
Hi,

The perl -d debug command works, the problem only occurs in VS Code :/
The debug doesn't work, even for a simple script like:
```
use strict;
use warnings;

print "hello";
```

**Comment by raix** [comment]
What os and perl version + distribution(on windows activeperl etc.)?
Please dump the `launch.conf` with the perl debug settings.

I'll try to reproduce asap

**Comment by Resousse** [comment]
I'm running this on windows 10 (x64) : perl 5, version 24, subversion 1 (v5.24.1) built for MSWin32-x86-multi-thread-64int, I installed strawberry-perl-5.24.1.1-32bit
Here my launch.conf file : 
```
{
    "version": "0.0.5",
    "configurations": [
        {
            "type": "perl",
            "request": "launch",
            "exec": "perl",
            "execArgs": [],
            "name": "Perl-Debug",
            "root": "${workspaceRoot}/",
            "program": "${workspaceRoot}/${relativeFile}",
            "inc": [],
            "args": [],
            "stopOnEntry": true
        }
    ]
}
```

**Comment by raix** [comment]
Please try:
```json
{
    "version": "0.0.5",
    "configurations": [
        {
            "type": "perl",
            "request": "launch",
            "exec": "perl",
            "execArgs": [],
            "name": "Perl-Debug",
            "root": "${workspaceRoot}",
            "program": "${relativeFile}",
            "inc": [],
            "args": [],
            "stopOnEntry": true
        }
    ]
}
```

**Comment by Resousse** [comment]
Nop, still the same error :/

**Comment by raix** [comment]
ok, thanks @Resousse I'll see if I can replicate tomorrow

**Comment by raix** [comment]
Bugger - I've been able to replicate on linux but not on mac... I'll see if I can get this into the test suite, eta 2 days

**Comment by raix** [comment]
Basic tests for adapter is added, and breaks on some linux versions + windows (activeperl + strawberry).
The tests have one failure in common, but linux perl 5.14 fail in two extra.

I'll add more tests, bump dependencies and add a debugger log/trace option in the `launch.json` for better insights - I'll release the trace option etc. in `0.2.1`

**Comment by Resousse** [comment]
Thanks for your reactivity, sorry to not being able to help you :(

**Comment by raix** [comment]
Don't worry about it - When I add the "trace" option you will be able to help :)

**Comment by raix** [comment]
Actually @Resousse: I got it working fine on linux, might be the same thing causing the issue - could you try this:
```json
{
    "version": "0.0.5",
    "configurations": [
        {
            "type": "perl",
            "request": "launch",
            "exec": "perl",
            "execArgs": [],
            "name": "Perl-Debug",
            "root": "",
            "program": "${workspaceRoot}/${relativeFile}",
            "inc": [],
            "args": [],
            "stopOnEntry": true
        }
    ]
}
```
*Setting root path to empty and program to absolute path seems to help - You might need to test both unix and windows path separator*

**Comment by Resousse** [comment]
Oh! It worked when I replaced the "/" by "\\" in the program attribute!
I have the following config:
```
{
    "version": "0.0.5",
    "configurations": [
        {
            "type": "perl",
            "request": "launch",
            "exec": "perl",
            "execArgs": [],
            "name": "Perl-Debug",
            "root": "${workspaceRoot}/",
            "program": "${workspaceRoot}\\${relativeFile}",
            "inc": [],
            "args": [],
            "stopOnEntry": true
        }
    ]
}
```
Thanks a lot for the inspection!

**Comment by raix** [comment]
@Resousse interesting! Thanks for the extra clue - I'll have a fix out for it

**Comment by dmayley** [comment]
@raix, clearing the root has the extension working for me!!  I have been trying to get this to for a few days now!!  Using Linux.  Linux and Perl are both new to me, so I thought it was something I had incorrect.
Appreciate your efforts on this extension! Thank you!

**Comment by raix** [comment]
@DonM14 thanks for the confirmation, I'll have an update out soon
*(There are some inconsistencies across versions of perl/platforms and distributions so feedback is appreciated)*

**Comment by raix** [comment]
I've been working hard on `v0.2.1` fixing this issue - it should be solved now. `root` is only used to set the current working directory, while `program` points to the program.
The configuration should also be initialized with the system path separator *not verified on windows yet - but code complete*

Closing, but please let me know if it's still causing issues
