### ISSUE TITLE
Debug not working with NYTProf active

### ISSUE THREAD

**Issue by mihaipopescu** [raix/vscode-perl-debug#20]
Error `Could not connect to debugger, connection closed` was reported in the debug console.

Steps to reproduce:
OS: Windows10 64bit
Dist: ActiveState Perl v5.24.1 (MSWin32-x86-multi-thread-64int)
Environment: `PERL5OPT=-d:NYTProf`

Deleting the environment variable fixed the issue.

**Comment by raix** [comment]
@mihaipopescu thanks for reporting, I'm curious if the debugger should overwrite the `PERL5OPT`?
*(Allowing the user to set options in the vs settings instead)*

**Comment by raix** [comment]
@mihaipopescu this should be fixed in `v0.2.1` `PERL5OPT` are no longer passed on pr. default - need to set environment variables in settings.

Let me know if it's not working

**Comment by mihaipopescu** [comment]
I'll check. Thanks @raix.
