### ISSUE TITLE
Relax exceptions "redefine"

### ISSUE THREAD

**Issue by raix** [raix/vscode-perl-debug#22]
We might want to warn instead throwing an exception
* `onException: Subroutine ... redefined`

Need to investigate further

**Comment by raix** [comment]
We might want to change warning level - or figure out if we can catch warnings

**Comment by raix** [comment]
overwrite warn in init block eg. in `.perldb`

**Comment by pwr22** [comment]
That's not an exception, it's a warning. Perl behavior is to continue on warnings usually so I don't think its the right thing to do to elevate them to being fatal

**Comment by pwr22** [comment]
Exceptions in Perl are thrown using `die` and will stop program execution if they aren't handled

**Comment by raix** [comment]
yep - but they are both "catched" and triggers the debugger to halt - it's something to improve on (just really annoying atm)

**Comment by hoehrmann** [comment]
As of v0.5.0 the extension no longer sees warnings. I think this can be closed.
