### ISSUE TITLE
launch.json problems

### ISSUE THREAD

**Issue by sorinmustaca** [raix/vscode-perl-debug#23]
I have VS 1.12.2 on Win10 x64.
I installed the debugger and I am experiencing the following issues:
- out of the box, I am asked to create a configuration.
- I have no idea how this thing works, so without too much thinking, I changed the code like this:

{
    "version": "0.2.0",
    "configurations": {
        "version": "0.0.5",
        "configurations": [
            
            {
                "type": "perl",
                "request": "launch",
                "exec": "C:\\Perl\bin\\perl.exe",
                "execArgs": [],
                "name": "Perl-Debug",
                "root": "${workspaceRoot}/",
                "program": "${workspaceRoot}/${relativeFile}",
                "inc": [],
                "args": [],
                "stopOnEntry": true
            }
        ]
    }
}

- After this, I get the error:
t.configurations.filter is not a function

And I can't debug ...

Any ideas?

**Comment by raix** [comment]
Hi @sorinmustaca can you give https://github.com/raix/vscode-perl-debug/issues/19#issuecomment-297756902 a go?

I've been preparing a new release the past two weeks improving things *just waiting for tests to pass*

**Comment by sorinmustaca** [comment]
Here is the solution:

{
    "version": "0.2.0",
        "configurations": [
            
            {
                "type": "perl",
                "request": "launch",
                "exec": "C:\\Perl\\bin\\perl.exe",
                "execArgs": [],
                "name": "Perl-Debug",
                "root": "${workspaceRoot}/",
                "program": "${workspaceRoot}/${relativeFile}",
                "inc": [],
                "args": [],
                "stopOnEntry": true
            }
        ]
    
}

I can at least start the debugger now :)

However, it is still not working as it should.
The debugger is started in the wrong folder: the folder of the solution, not where the perl source code is.

I have a structure like this:
/
- /f1
- /f2
-/src -> this is where my code is: **test.pl** which includes a **utils.pm**, in the same folder.

I loaded in VSCode the folder from the root.
When I debug, I see that VSCode executes
perl -d src/test.pl
and test.pl fails to find Utils.pm, despite the fact that i use an use lib "./";

After I change the start folder to src/ then it returns this error:
Error
Error: spawn C:\Perl\bin\perl.exe ENOENT

**Comment by sorinmustaca** [comment]
Ah, I found the solution in the other posts...
{
    "version": "0.2.0",
        "configurations": [
            
            {
                "type": "perl",
                "request": "launch",
                "exec": "C:\\Perl\\bin\\perl.exe",
                "execArgs": [],
                "name": "Perl-Debug",
                "root": "${workspaceRoot}",
                "program": "${relativeFile}",
                "inc": [],
                "args": [],
                "stopOnEntry": true
            }
        ]
    
}

**Comment by raix** [comment]
@sorinmustaca I've released `0.2.1` this should be solved both in creating proper initial settings for windows users and fixed path resolver internally.

Closing this, but let me know if it's still causing issues
