### ISSUE TITLE
Debugger launched but Visual Studio Code features not working

### ISSUE THREAD

**Issue by nikolas-x** [raix/vscode-perl-debug#31]
I am using Windows 10 and Perl 5.8.4. I installed the plugin on my Visual Studio Code and I tried to run the debugger. It looks like the perl debugger is run successfully, but none of the features of the plugin are working. For example, there is nothing under "Variables" or "Call Stack" and the current line is not shown in the editor. 

Here I ran the debugger and clicked "Step into" a few times. You can see that the Perl Debugger is running correctly but none of the Visual Studio Code features are working:

![vscode debug](https://user-images.githubusercontent.com/13508810/31700357-7ca2d07c-b414-11e7-9fa5-8062bd584bb9.png)

Additionally, setting breakpoints has no effect. The "launch.json" is unchanged from the default generated one:
```
{
        "version": "0.0.6",
        "configurations": [
            {
                "type": "perl",
                "request": "launch",
                "exec": "perl",
                "execArgs": [],
                "name": "Perl-Debug",
                "root": "${workspaceRoot}\\",
                "program": "${workspaceRoot}\\${relativeFile}",
                "inc": [],
                "args": [],
                "env": {},
                "stopOnEntry": false
            }
        ]
    }
```

I also installed the PadWalker plugin and confirmed that is configured correctly (I am able to import PadWalker and call PadWalker functions from my code), but this did not fix the problem. 

I guess it could be because my version of Perl is old, but I'm not able to use a newer version at my workplace (I'll try again later from home with the latest version).

**Comment by raix** [comment]
@nikolas-x what distribution of perl are you using on windows?

**Comment by nikolas-x** [comment]
ActiveState Perl

**Comment by raix** [comment]
Thanks @nikolas-x it might be that vs code broke stuff in the debug api, have to check

I haven't yet found a way to add active perl versions older than 5.24.1 to the test matrix https://github.com/raix/vscode-perl-debug/blob/master/appveyor.yml#L29 *(as I remember they remove older versions from download)*

**Comment by mbphsong** [comment]
I have Strawberry Perl version 5.24.1 on Windows 10 and have part of the same problem - nothing under "Variables" or "Call Stack" (although mine does show which line it is on and breakpoints work).

**Comment by raix** [comment]
@mbphsong do you have padwalker installed?

**Comment by mbphsong** [comment]
Ah!  I do remember seeing that, but it got lost in my frustration.  That fixed it! :-)

**Comment by raix** [comment]
@mbphsong super - yeah - I need to figure out how to trigger an info notification checking for padwalker

**Comment by raix** [comment]
I've added a notification in the "variable inspector" should prevent future issues. (it should be released if all tests pass on CI)

**Comment by raix** [comment]
I'm closing this issue - v0.4.0 will now show a message in the "variable inspector" if padwalker is not installed. Let me know if it doesn't solve the issue

**Comment by kleveingolstadt** [comment]
Hi, the padwaker detection is not working in all cases. We are working under Ubuntu 14 and also under Windows with Strawberry Perl version 5.20.2 with same package installation. Under Windows it is working, but under Ubuntu I get the not installed message. If I hack the debug extention then I can see the variables list, because we have installed Padwalker 2.2 version. Ideas?

**Comment by kleveingolstadt** [comment]
Hi, next problem where I have no idea what happens. I have the following code:
use strict;
use warnings;
use Getopt::Long qw(GetOptions);
print "##########################\n";
#print $DB::OUT eval { require PadWalker; PadWalker->VERSION() } . "\n";
print PadWalker->VERSION() . "\n"; #we have version 2.1
print "##########################\n";
my %options;
my $rcode = Getopt::Long::GetOptions(
	\%options,
	"testopt1:s",
	"testopt2:s",
);
#
# Check options
#
if (!($rcode)) {
	print "Fail! Should get a return value and the option hash should not empty!\n";
}else{
       print"It's working \n";
}	  

This code is working in other debuggers (tk and Eclipse). $rcode should be '1' and %options should include my options.  I try it under Ubuntu and Windows. Same result!

**Comment by raix** [comment]
The extension uses `print $DB::OUT eval { require PadWalker; PadWalker->VERSION() }` for getting the padwalker version. If the result from this call is undefined then no padwalker is installed.

We should open a new  issue for the padwalker check, I'm not sure about the "check option" part - might be worth for us to add a test file.

**Comment by kleveingolstadt** [comment]
Hi, thanks for feedback!  ;-)  I have check futher and I step in the Getopt::Long::GetOptions function. The return value is '1', but the value will not taken over to $rcode and %options.
