### ISSUE TITLE
variables not shown in variable explorer when debugging

### ISSUE THREAD

**Issue by jannick0** [raix/vscode-perl-debug#37]
Unfortunately there are variables shown in the variable explorer when debugging, while hovering over each one reveals the current value. Is this a bug or rather a config issue and I have missing something? @raix Or is this rather an interface issue of the perl debugger you are alluding to in the ReadMe.md?

I am degugging the [sample perl snips](https://github.com/raix/vscode-perl-debug/tree/master/src/tests/data) used in the nice video teaser.

VS Code 1.19.3 / Perl-Debug 0.2.5 / Windows 64bit - Strawberry perl 5.26.1 and ...
```json
// launch.json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "perl",
            "request": "launch",
            "exec": "C:/strawberry-perl/perl/bin/perl.exe",
            "execArgs": [],
            "name": "Perl Debug",
            "root": "${workspaceRoot}/",
            "program": "${workspaceRoot}/${relativeFile}",
            "inc": ["."],
            "args": [],
            "stopOnEntry": true
        }
    ]
}
```

**Comment by jannick0** [comment]
... just found out that watching variables works.

**Comment by raix** [comment]
Do you have padwalker installed?

**Comment by jannick0** [comment]
Aaah - no, but now it is and the debugger is working like a charm.

Perhaps adding that to the prerequisite checks of `perl-debug`?

**Comment by raix** [comment]
@jannick0 super!

yeah - I wanted to have a info box open with a warning - basically need to check on each run in case of removal. It's on the todo list, but haven't had the time yet

**Comment by jannick0** [comment]
That would be great! BTW: PadWalker appeared to do some time consuming work when fired up the first time. If that is true, the user could be warned about that once it is installed.
