### ISSUE TITLE
Cannot feed input into STDIN from debug console

### ISSUE THREAD

**Issue by NSExceptional** [raix/vscode-perl-debug#40]

**Comment by HalCraig** [comment]
I  am seeing this problem also.  My json
"version": "0.2.0",
    "configurations": [
        {
            "type": "perl",
            "request": "launch",
            "name": "Perl-Debug local",
            "program": "${workspaceFolder}/${relativeFile}",
            "exec": "perl",
            "execArgs": [],
            "root": "${workspaceRoot}/",
            "inc": [],
            "args": [],
            "env": {},
            "stopOnEntry": true
        },
        {
            "type": "perl",
            "request": "launch",
            "name": "Perl-Debug remote",
            "program": "${workspaceFolder}/${relativeFile}",
            "root": "${workspaceRoot}/",
            "stopOnEntry": true,
            "port": 5000
        }
    ]
}

**Comment by HalCraig** [comment]
[HelloWorld (copy).txt](https://github.com/raix/vscode-perl-debug/files/2195091/HelloWorld.copy.txt)

**Comment by HalCraig** [comment]
Code:

use 5.014;
use strict;
use warnings;
our $a = "Hello World";

my $s;
print "Enter Name";
$s = <STDIN>;
chomp($s);
print $s;

**Comment by hoehrmann** [comment]
This has been fixed with https://github.com/raix/vscode-perl-debug/pull/64 I believe.

**Comment by NSExceptional** [comment]
Sweet! I'll close this then.
