### ISSUE TITLE
Be able to define PERL5LIB when debugging

### ISSUE THREAD

**Issue by ytnobody** [raix/vscode-perl-debug#5]
Hi. Thank you for create the clever extension for vscode.
I hope to define PERL5LIB when debugging with vscode-perl-debug extension.
Please examining.

Best regards.

**Comment by raix** [comment]
Hi, do you mean like setting -Xlib or the env variable?

**Comment by raix** [comment]
@ytnobody Can you try v0.1.2 - I've added a setting `inc` in the launch config file - it can be an array of one or more path's to include directories.
*Note that #3 is about building a proper file/module resolver - so I have to learn how perl resolves modules*

**Comment by ytnobody** [comment]
It looks so cool !

But... 
I tried v0.1.2 and I encountered a following fault on MacOSX.

![2016-11-29 15 03 05](https://cloud.githubusercontent.com/assets/278841/20698556/2ca323f6-b645-11e6-96f1-6b9d2f4fe940.png)

I know. It means that failed to set specified paths to INC.

Maybe, we have to swap `-I ${incPath???}` and `-d ${command.AskForProgramName}` to solve this issue.

I tried it on bash.
```
bash-3.2$ perl -d t/11_message_request.t -I/Users/azuma.satoshi/Net-Azure-EventHubs/lib

Loading DB routines from perl5db.pl version 1.49
Editor support available.

Enter h or 'h h' for help, or 'man perldebug' for more help.

Can't locate Net/Azure/EventHubs.pm in @INC (you may need to install the Net::Azure::EventHu
bs module) (@INC contains: /Users/azuma.satoshi/.plenv/versions/5.22/lib/perl5/site_perl/5.2
2.0/darwin-2level /Users/azuma.satoshi/.plenv/versions/5.22/lib/perl5/site_perl/5.22.0 /User
s/azuma.satoshi/.plenv/versions/5.22/lib/perl5/5.22.0/darwin-2level /Users/azuma.satoshi/.pl
env/versions/5.22/lib/perl5/5.22.0 .) at t/11_message_request.t line 5.
 at t/11_message_request.t line 5.
        main::BEGIN() called at t/11_message_request.t line 5
        eval {...} called at t/11_message_request.t line 5
BEGIN failed--compilation aborted at t/11_message_request.t line 5.
 at t/11_message_request.t line 5.
Debugged program terminated.  Use q to quit or R to restart,
use o inhibit_exit to avoid stopping after program termination,
h q, h R or h o to get additional info.
  DB<1> q
```
It failed to set @INC. It is as expected.

Afterwords, I tried again with swapped these options.
```
bash-3.2$ perl -I/Users/azuma.satoshi/Net-Azure-EventHubs/lib -d t/11_message_request.t

Loading DB routines from perl5db.pl version 1.49
Editor support available.

Enter h or 'h h' for help, or 'man perldebug' for more help.

main::(t/11_message_request.t:7):       my $hub = Net::Azure::EventHubs->new(
main::(t/11_message_request.t:8):           connection_string => 'Endpoint=sb://mysvc.servic
ebus.windows.net/;SharedAccessKeyName=mykey;SharedAccessKey=AexamplekeyAEXAMPLEKEYAexampleke
yAEXAMPLEKEY=;EntityPath=myentity',
main::(t/11_message_request.t:9):       );
  DB<1> q
```
Looks good :)

**Comment by raix** [comment]
Ok so options need to be swapped, Ill fix that

**Comment by raix** [comment]
@ytnobody hopefully 0.1.3 should solve the argument order

**Comment by ytnobody** [comment]
Wow, looks good! :+1: 🎊 
![2016-12-01 19 14 08](https://cloud.githubusercontent.com/assets/278841/20790137/6a2fa51c-b7fa-11e6-96a3-2b455fac5ee3.png)

Thank you!!!!

**Comment by raix** [comment]
0.1.6 is out adding support for the PERL5LIB environment variable - just in case :)
