### ISSUE TITLE
Variable View, Highlighted line not showing; PadWalker installed 

### ISSUE THREAD

**Issue by HayashiEsme** [raix/vscode-perl-debug#50]
![image](https://user-images.githubusercontent.com/24488417/52550215-046c3480-2e12-11e9-9526-bfb9c86b823b.png)
Hi there, 

I'm getting similar issues to /issues/48 but I do actually have PadWalker installed. Not sure what's wrong here. If it does help, I am using WSL, and also has PadWalker installed too; and I'm not using WSL to debug here 

Running Windows 10, Strawberry Perl 5.14.2, PadWalker 2.3 and VSCode 1.31.0 

Any help would be great, thanks:)

**Comment by HayashiEsme** [comment]
I solved my problem, the perl installed was too old to work with the extension. Hopefully someone finds this useful one day.

**Comment by raix** [comment]
Ah, interesting - actually thinking if we should add a feature to warn about old versions?
(this extension heavily relies on the output from perldb / padwalker versions - to be honest they are not consistent across platforms/distributions)

**Comment by HayashiEsme** [comment]
That'd be great. If you're going to have trouble finding the time to implement that feature, a little warning at the extension page would do the trick too
