### ISSUE TITLE
Breakpoints vs relative paths

### ISSUE THREAD

**Issue by hoehrmann** [raix/vscode-perl-debug#51]
The Perl debugger seems to have a rather simplistic path lookup mechanism. When you have something like

```perl
BEGIN {
  use lib './foo/bar';
  ...
}
```

then the Perl debugger `f` command is unable to switch to files under `foo/bar` using their absolute paths. So when you try to set a breakpoint in vscode in files there, this extension currently issues `f <absolute path>` which then fails to set a breakpoint.

```
x $INC{'Grammar/Graph2.pm'}
0  'Grammar-Graph2/lib/Grammar/Graph2.pm'
f /home/.../Grammar/Graph2.pm
No file matching '/home/.../Grammar/Graph2.pm' is loaded.
```

Perhaps this could be addressed by looking at the output of the `M` command or by checking `%INC` or by looking at the error message given by `f` and perhaps re-trying with an abbreviated path or a combination thereof.

**Comment by raix** [comment]
I don't like the current way paths are implemented in perl debugger atm. it's not stable / testable.
I would love to see a pr solving this :)
