### ISSUE TITLE
Calling warn stops the debugger

### ISSUE THREAD

**Issue by hoehrmann** [raix/vscode-perl-debug#52]
When you have Perl code doing something like

```perl
warn "foo";
```

you get 

```
onException: fooDebugger connection closed
```

upon hitting the warning.

I gather this is due to code marked with `xxx`.

**Comment by hoehrmann** [comment]
I looked into this a bit and a `warn` as above ultimately causes output that matches

```ts
export const codeErrorRuntime = /([\S|\s]+) at (\S+) line ([0-9]+)\.$/;
```

It seems the Perl debugger does not really allow implementing vscode features like »Break on all exceptions« and »Break on uncaught exceptions« and so far I see no reason to react to such output at all. As above, the current implementation terminates the debug session and prints a message claiming an exception occurred; if this really was an uncaught exception the debuggee would terminate anyway.

**Comment by raix** [comment]
I think the stream might actually get terminated by perldb but I could be wrong?

**Comment by hoehrmann** [comment]
This is still the case, even with the newly separated stdio changes. Seems this might in part be accidental behaviour due to changes in `perl5db.pl` for which I opened a bug report https://rt.perl.org/Public/Bug/Display.html?id=133875 - basically, the debugger overrides the `warn` functions so that debuggee warnings end up in the debugger stream, unlike `die` messages.

I think I will make a PR to remove the exception detection code, warnings are not really exceptions, and actual uncaught exceptions are not detectable without new and additional effort anymore. It might be possible to use `ExceptionBreakpointsFilter` and `perl5db.pl` `warnLevel` and `dieLevel` options, but this whole area is a bit of a minefield.

**Comment by raix** [comment]
Maybe we ask the user to update perl5db.pl or somehow only support some versions
