### ISSUE TITLE
Tests expect @INC to include "."

### ISSUE THREAD

**Issue by hoehrmann** [raix/vscode-perl-debug#53]
Perl 5.26.0 removed `.` from `@INC`. The tests current have to be run using e.g.

```bash
PERL5LIB=. jest
```

Otherwise the `connection.test.ts` tests all fail because `Module.pm` cannot be found.

**Comment by raix** [comment]
Ah - good catch - this is one of the areas where the extension could be a bit smarter

**Comment by hoehrmann** [comment]
I would probably change the tests to use `FindBin` und `use lib "$FindBin..."` which is a fairly standard idiom (https://perldoc.perl.org/FindBin.html), would that be acceptable to you?
