### ISSUE TITLE
Printing to STDERR vs $DB::OUT

### ISSUE THREAD

**Issue by hoehrmann** [raix/vscode-perl-debug#55]
This does not and probably cannot work with remote debugging:

```ts
	async getVariableReference(name: string): Promise<string> {
		const res = await this.request(`print STDERR \\${name}`);
		return res.data[0];
	}

	async getExpressionValue(expression: string): Promise<string> {
		const res = await this.request(`print STDERR ${expression}`);
		return res.data.pop();
	}
```

It seems to me that this should instead be

```perl
print { $DB::OUT } ...
```

to make sure it does not interfere, as much as possible anyways, with the debuggee, and actually ends up on the socket when using remote debugging.

**Comment by raix** [comment]
Yes when remote debugging theres an issue in getting the output.
Normal local development we have 3 streams
* STDIN - execute commands
* STDOUT - application output
* STDERR - debugger output

When doing remote debugging we only have two
* STDIN - execute commands
* STDOUT + STDERR - debugger output / application output (an issue)

If we could prefix data on the stdout / stderr we could separate the data into two streams again.

Let me know if this makes sense?

**Comment by hoehrmann** [comment]
As I understand it, in the remote case, you have a TCP stream where you send debugger commands to and retrieve debugger output from. The debuggee's `stdout` and `stderr` are entirely independent. 

When you hover over a variable, the code above causes the variable value to be printed on `stderr` on the remote machine and you get nothing on the TCP stream. With

```perl
print { $DB::OUT } ...
```

the variable value would be printed on the TCP stream and could be read from there by the extension.
