### ISSUE TITLE
Separate perl5db stdio from debuggee stdio 

### ISSUE THREAD

**Issue by hoehrmann** [raix/vscode-perl-debug#58]
Ideally the extension should have separate communication channels for debugger and script. Right now it mixes them, and when a script prints to `stderr` the contents is interpreted by the extension. As an example,

```perl
print STDERR "Execution of 1.js aborted due to compilation errors.\n";
```

Currently this has fatal consequences, but should not have any consequences at all, scripts should use `stderr` as they see fit without any effect on the debugger.

It ought to be possible to separate the two channels, currently I am experimenting with

```diff
diff --git a/src/adapter.ts b/src/adapter.ts
index f838c29..055593d 100644
--- a/src/adapter.ts
+++ b/src/adapter.ts
@@ -343,6 +343,9 @@ export class perlDebuggerConnection {
                        }
                });
 
+               await this.streamCatcher.request('do { open STDERR, "+>&=", 4; DB::_autoflush(STDERR); };');
+               await this.streamCatcher.request('do { open STDOUT, "+>&=", 3; DB::_autoflush(STDOUT); };');
+
                // Depend on the data dumper for the watcher
                // await this.streamCatcher.request('use Data::Dumper');
                await this.streamCatcher.request('$DB::single = 1;');
diff --git a/src/localSession.ts b/src/localSession.ts
index b8f0fc3..922e324 100644
--- a/src/localSession.ts
+++ b/src/localSession.ts
@@ -21,6 +21,7 @@ export class LocalSession implements DebugSession {
                const spawnOptions = {
                        detached: true,
                        cwd: cwd || undefined,
+                       stdio: ["pipe", "pipe", "pipe", "pipe", "pipe"],
                        env: {
                                COLUMNS: 80,
                                LINES: 25,
@@ -34,6 +35,17 @@ export class LocalSession implements DebugSession {
                this.stdout = session.stdout;
                this.stderr = session.stderr;
                this.pid = session.pid;
+
+               const stdio = session.stdio as any[];
+
+               stdio[3].on("data", x=> {
+                       console.log("stdio3 data: " + x);
+               });
+
+               stdio[4].on("data", x=> {
+                       console.log("stdio4 data: " + x);
+               });
+
                this.on = (type, callback) => session.on(type, callback);
                this.kill = () => session.kill();
                this.title = () => `${perlCommand} ${commandArgs.join(' ')}`;
```

This should also allow capturing `stdout`/`stderr` in remote debugging scenarios. But there are quite many unknowns at this point.

* How does mixing debugger `stdin` and script `stdin` work at the moment, how should it work.
* With remote debugging, do users want to redirect output from their remote terminal into vscode?
* Could they have both, i.e. duplicating rather than redirecting remote terminal output?
* Where should script `stdout` and script `stderr` actually go in vscode? Right now in the debug console script `stderr` is suppressed and `stdout` mixed with debugger output.
* What are the right `open` modes to use? What if the `open` calls fail?
* Are there any adverse consequences doing this?
* Does this work on Windows?

Might be worth trying something like this behind a default-off configuration option?

Edit: Come to think of it, might be worth considering making local debugging also use a remote debugging setup (call `perl -d` with a remote port set), that might simplify a few things.

**Comment by hoehrmann** [comment]
> How does mixing debugger `stdin` and script `stdin` work at the moment, how should it work.

Local debugging with e.g.

```perl
my $line = <STDIN>;
print "You said: $line\n";
```

results in a hang, you can enter stuff in the debug console, but then nothing happens until you switch to some other tab and then back to the debug console, where you can then see that your input made it to the debugger, not the debuggee. With remote debugging everything works as expected (you can enter your input in the remote terminal where your input is echoed and printed).

**Comment by raix** [comment]
I think the real problem is in remote debugging - because the sdtout and stderr are combined

**Comment by hoehrmann** [comment]
In remote debugging, the extension currently has no access to the debuggee's stdio, it only talks to the debugger which does not forward anything. Simple test setup, one terminal with the listener `nc -l -p 5000` and then one with the rest `PERLDB_OPTS="RemotePort=localhost:5000" perl -d -E "say STDOUT 'stdout'; say STDERR 'stderr'"`.

In the listener terminal you get an interactive debugger session like so:

```
Loading DB routines from perl5db.pl version 1.53
Editor support available.

Enter h or 'h h' for help, or 'man perldebug' for more help.

main::(-e:1):	say STDOUT 'stdout'; say STDERR 'stderr'
  DB<1> l
1==>	say STDOUT 'stdout'; say STDERR 'stderr'
  DB<1> r
Debugged program terminated.  Use q to quit or R to restart,
use o inhibit_exit to avoid stopping after program termination,
h q, h R or h o to get additional info.
  DB<1> q
```

While in the other terminal you get the stdio from the script:

```bash
stdout
stderr
```

**Comment by raix** [comment]
the perl debugger extension is running the perlDB in interactive mode - I would be fine with one output stream (instead of both stderr + stdout)

But we would have to figure out a way to separate the two eg. by prefixing both steams so that we can tell the difference between debugger output and application output.

This works locally using 2 output steams but not remotely because we only have one. (I agree that if we can solve it for remote debugging we could generally settle with one output stream - both locally and remote)

**Comment by hoehrmann** [comment]
Turns out vscode has added a »Terminal« feature since you made the extension. Investigating along these lines now:

```diff
diff --git a/src/adapter.ts b/src/adapter.ts
index f838c29..f093fbe 100644
--- a/src/adapter.ts
+++ b/src/adapter.ts
@@ -296,11 +301,10 @@ export class perlDebuggerConnection {
                this.logOutput(`Platform: ${process.platform}`);
                this.logOutput(`Launch "perl -d ${sourceFile}" in "${cwd}"`);
 
                // xxx: add failure handling
                if (!options.port) {
                        // If no port is configured then run this locally in a fork
-                       this.perlDebugger = new LocalSession(filename, cwd, args, options);
+                       this.perlDebugger = new RemoteSession(0);
                        this.logOutput(this.perlDebugger.title());
                } else {
                        // If port is configured then use the remote session.
@@ -308,6 +312,22 @@ export class perlDebuggerConnection {
                        this.perlDebugger = new RemoteSession(options.port);
                }
 
+               await new Promise(
+                       resolve => this.perlDebugger.on("listening", res => resolve(res))
+               );
+
+               const foo : DebugProtocol.RunInTerminalRequestArguments = {
+                       cwd: cwd,
+                       args: ["perl", "-d", filename].concat(args),
+                       env: {
+                               PERLDB_OPTS: `RemotePort=localhost:${this.perlDebugger.port}`,
+                               ...options.env
+                       }
+               };
+
+               session.runInTerminalRequest(foo, 5000, response => {
+               });
+
                this.commandRunning = this.perlDebugger.title();
 
                this.perlDebugger.on('error', (err) => {
diff --git a/src/remoteSession.ts b/src/remoteSession.ts
index bac85ff..a86b86b 100644
--- a/src/remoteSession.ts
+++ b/src/remoteSession.ts
@@ -13,6 +13,7 @@ export class RemoteSession implements DebugSession {
        public kill: Function;
        public title: Function;
        public dump: Function;
+       public port: Number | null;
        private event = new EventEmitter();
 
        constructor(port: number) {
@@ -71,7 +72,11 @@ export class RemoteSession implements DebugSession {
                        });
                });
 
-               server.listen(port, '0.0.0.0'); // Listen to port make it remotely available
+               server.listen(port, '0.0.0.0', () => {
+                       this.event.emit('listening', ()=>{});
+                       this.port = server.address().port;
+               }); // Listen to port make it remotely available
+
                server.on('error', data => {
                        this.event.emit('error', data);
                        this.kill();
```

That gives you a debug console where you interact with the debugger, and a terminal where you interact with the debuggee. The debuggee is launched there like

```bash
% cd /.../ ; env \
  "PERLDB_OPTS=RemotePort=localhost:41771" \
  "PATH=... "PERL5LIB=" \
  perl -d /.../example.pl
```

**Comment by raix** [comment]
In the debug console you also have the ability to write (in the bottom there is a text input) - That said the terminal might be good for debugging the extension - but we still need to figure out a way to separate the debugger output and the application output from the single stream when remote debugging. Eg. To make sure the extension only acts on debug output and leave the application output as is.

**Comment by hoehrmann** [comment]
With https://github.com/raix/vscode-perl-debug/commit/a10fa81a8664c2103613435047ae4bfa077220a5 this is basically fixed.
