### ISSUE TITLE
launch.json entry

### ISSUE THREAD

**Issue by pesr0412** [raix/vscode-perl-debug#7]
I have installed this extension, but I don't see any entry in the launch.json that allows for the debug process to work, what are the parameters to use to make an entry in the launch.json?

**Comment by raix** [comment]
Not sure what you mean - the default launch asks for the file to run when debugging.

Example:
```json
{
    "version": "0.0.2",
    "configurations": [
        {
            "type": "perl",
            "request": "launch",
            "exec": "perl",
            "name": "Perl-Debug",
            "root": "${workspaceRoot}/",
            "program": "${workspaceRoot}/${command.AskForProgramName}",
            "inc": ["lib/foo", "lib/bar"],
            "stopOnEntry": true
        }
    ]
}
```

btw. what os are you on? *(There are currently issues on windows and some versions of perl on linux - mac os should be ok - I'm surprised about the inconsistency)*

**Comment by pesr0412** [comment]
that default configuration you just shared is not in my launch.json file, there was no default configuration for perl on my visual studio code, I will use the one you just put and modify accordingly. Thanks!

**Comment by raix** [comment]
you could also remove the launch.json file and have vs code generate it again for you

**Comment by raix** [comment]
https://code.visualstudio.com/docs/editor/debugging#_launch-configurations
*(you can click on the configuration gear)*

**Comment by pesr0412** [comment]
yeah, I will have this thing figured out, thanks so much for the help provided :)

**Comment by papaiatis** [comment]
I was missing the default configuration as well from launch.json. 
I'm on Linux with perl 5.20 installed. VS Code 1.7.1

Added it manually made debugging working!

**Comment by raix** [comment]
@papaiatis thanks - good point about relative file - I could add both as default configs (wondering why the main default config isn't set on linux) - did you have to create the launch.json file or was it created when clicking the gear icon?

**Comment by papaiatis** [comment]
@raix I already had the launch.json file because I was debugging Python code earlier. I added the perl debug config to the end of this file.

**Comment by raix** [comment]
Using `relativeFile` in https://github.com/raix/vscode-perl-debug/commit/e146201ce060bfa48506fa3db7e9134a39a430de *(less annoying default)*

**Comment by raix** [comment]
Not sure if this is an actual issue - If the project has a `launch.json` already you need to add the perl debug config manually (it's a vs code "feature")

**Comment by raix** [comment]
I'm closing this - as I'm not able to replicate, please let me know if it's still an issue *I might not be able to solve it - but we can add documentation in the wiki helping others*
