### ISSUE TITLE
Add depedency checks

### ISSUE THREAD

**Issue by raix** [raix/vscode-perl-debug#8]
Have vs code notify the user if we are missing dependencies

* `PadWalker` module is required for variable inspection
* `perl`

**Comment by mgreter** [comment]
In my situation everything seemed to work (Strawberry Perl) beside the variable inspection, so I thought I'd try to fix that. Once I started to debug the debug adapter via "Run Server" the issue became quite obvious: `PadWalker module not found - please install`.

Unfortunately that message doesn't normally find its way back to the user!
This should at least be (prominently) documented in the main README.md!

Thanks for creating this usefull piece of Software! Perl FTW 😉

**Comment by raix** [comment]
argh - sorry about that - I've added it in the readme - it should be possible to show a snackbar if a dependency is missing, but I haven't had time to investigate further (I think to remember the python extensions doing dependency checks - so it might just be a configuration thing)

**Comment by raix** [comment]
I'm closing this issue - v0.4.0 will now show a message in the "variable inspector" if padwalker is not installed. Let me know if it doesn't solve the issue
